version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - nestjs-network
  payment_ms:
    image: payment-ms:1.0.0
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      HTTP_PORT: 3000
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: payment-db
      AUTO_SEED: 'true'
      SHOULD_MOCK_USER: 'true'
      MOCK_USER_ID: 1
      MOCK_USER_IS_ADMIN: 'false'
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  nestjs-network: